// File generated by Liraza Assistant to bypass CLI issues
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Add Android/iOS config here if needed later
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    // TODO: 1. Go to Firebase Console -> Project Settings -> General -> Your Apps -> Web App
    // TODO: 2. Copy the "firebaseConfig" values and paste them below
    apiKey: 'PASTE_YOUR_API_KEY_HERE',
    appId: 'PASTE_YOUR_APP_ID_HERE',
    messagingSenderId: 'PASTE_YOUR_MESSAGING_SENDER_ID_HERE',
    projectId: 'PASTE_YOUR_PROJECT_ID_HERE',
    authDomain: 'PASTE_YOUR_AUTH_DOMAIN_HERE', // Optional but recommended
    storageBucket: 'PASTE_YOUR_STORAGE_BUCKET_HERE', // Optional
  );
}
